@baseUrl = https://shopping-lists-api.herokuapp.com
// API Key
@apiKey = ""
// ID der Liste hier eintragen
@listId = ""
// ID des Items hier eintragen
@itemId = ""

### Liste abrufen
GET {{baseUrl}}/api/v1/lists/{{listId}}



### Item zur Liste hinzufügen
POST {{baseUrl}}/api/v1/lists/{{listId}}/items
content-type: application/json

{ "name": "Bier" }



### Item auf Liste aktualisieren
PUT {{baseUrl}}/api/v1/lists/{{listId}}/items/{{itemId}}
content-type: application/json

{ "bought": true }



### Item aus Liste löschen
DELETE {{baseUrl}}/api/v1/lists/{{listId}}/items/{{itemId}}


### Alle Listen des Users abrufen (private)
GET {{baseUrl}}/api/v1/lists
Authorization: {{apiKey}}


### Neue Liste anlegen (private)
POST {{baseUrl}}/api/v1/lists
Authorization: {{apiKey}}
content-type: application/json

{ "name": "Neue Liste" }


### Liste löschen (private)
DELETE {{baseUrl}}/api/v1/lists/{{listId}}
Authorization: {{apiKey}}
